name: Build vsix and upload on pull request
on: 
    pull_request_target:
        types: [opened, synchronize, edited]
jobs:
  build-vsix-and-upload:
    name: build vsix and upload
    if: ${{ !github.event.pull_request.draft }}
    runs-on: windows-2019
    steps:
      #- name: wait for mergeable
      #  id: wait-for-mergeable
      #  uses: tonyhallett/ReleaseManager/wait_for_mergeable@main
      #  env:
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v2
      #  with:
      #      ref: ${{ steps.wait-for-mergeable.outputs.mergeCommitSha}}
                
      - name: set up msbuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: set up VSTest
        uses: darenm/Setup-VSTest@v1
      - name: nuget restore
        run: nuget restore DummyZipVsix.sln
      - name: build vsix
        run: |
          msbuild DummyZipVsix.sln /p:Configuration=Release /p:DeployExtension=False /verbosity:minimal 
      - name: upload vsix
        uses: actions/upload-artifact@v2
        with:
            name: DummyZip ( zipped vsix)
            path: ${{github.workspace}}\DummyZipVsix\bin\Release\DummyZipVsix.vsix
