name: log merge sha
on: 
    pull_request:
        types: [ opened, synchronize, edited]
jobs:
  log-merge-sha:
    name: log merge sha
    runs-on: windows-2019
    steps:
    - name: echo checkout values
      run: echo "ref - $GITHUB_REF sha $GITHUB_SHA merge $GITHUB_MERGE_SHA"
      env:
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_MERGE_SHA: ${{github.event.pull_request.merge_commit_sha}}

      
