name: Push artifact
on: [push]

jobs:
  upload-artifact:
    name: upload artifact
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: upload 
        uses: actions/upload-artifact@v2
        with:
            name: artifact
            path: ${{github.workspace}}\DummyZipVsix.sln
      
      

