name: test pull request issues
on: 
    pull_request:
        types: [opened, synchronize, edited]
jobs:
  test-pull-request-issues:
    runs-on: windows-2019
    steps:
      - name: Pull request issues
        if: ${{ !github.event.pull_request.draft }}
        uses: tonyhallett/ReleaseManager/get_pull_request_issue@main
        with:
            useCommitMessages: 'false'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo mergeable
        env:
            MERGEABLE: ${{ github.event.pull_request.mergeable }}
        run: echo 'mergeable $MERGEABLE'
      - name: echo mergeable state
        env:
            MERGEABLE_STATE: ${{ github.event.pull_request.mergeable_state }}
        run: echo 'mergeable state $MERGEABLE_STATE'
      - name: echo merge commit sha
        env:
            MERGEABLE_COMMIT_SHA: ${{ github.event.pull_request.merge_commit_sha }}
        run: echo 'merge commit sha $MERGEABLE_COMMIT_SHA'
