name: test pull request issues
on: 
    pull_request:
        types: [opened, synchronize, edited]
jobs:
  test-pull-request-issues:
    runs-on: windows-2019
    steps:
      - name: Pull request issues
        if: ${{ !github.event.pull_request.draft }}
        uses: tonyhallett/ReleaseManager/get_pull_request_issue@main
        with:
            useCommitMessages: 'false'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo repo
        run: This workflow on ${{ github.repository }} 
      - name: echo mergeable
        run: echo mergeable ${{ github.event.pull_request.mergeable }}
      - name: echo mergeable state
        run: echo mergeable state ${{ github.event.pull_request.mergeable_state }}
      - name: echo merge commit sha
        run: echo merge commit sha ${{ github.event.pull_request.merge_commit_sha }}
      
