name: Test version
on: 
    push:
    pull_request:
        types: [opened, synchronize, edited]
    
jobs:
  test-version:
    name: test version
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: get next version 
        id: next-version
        uses: paulhatch/semantic-version@v4.0.1
        with:
            short_tags: false
            branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || 'HEAD' }}
      - name: major minor build revision
        env:
            VSIXVersion: ${{steps.next-version.outputs.major}}.${{steps.next-version.outputs.minor}}.${{github.run_number}}.${{steps.next-version.outputs.patch}}
        run: echo ${{env.VSIXVersion}}
