name: test pull request issues
on: 
    pull_request_target:
        types: [opened, synchronize, edited]
jobs:
  test-pull-request-issues:
    runs-on: windows-2019
    steps:
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
            name: my-artifact
            path: path/to/artifact/world.txt
      - name: Wait for mergeable
        id: wait_for_mergeable
        uses: tonyhallett/ReleaseManager/wait_for_mergeable@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo when mergeable
        if: ${{ steps.wait_for_mergeable.outputs.mergeable}}
        run: echo mergeable
      - name: echo when not mergeable
        if: ${{ !steps.wait_for_mergeable.outputs.mergeable}}
        run: echo 'not mergeable'
      - name: Pull request issues
        if: ${{ !github.event.pull_request.draft && steps.wait_for_mergeable.outputs.mergeable}}
        uses: tonyhallett/ReleaseManager/get_pull_request_issue@main
        with:
            useCommitMessages: 'false'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
      
